build_environment: 'master'
yum_repository: 'openstack-rhel'

cc_external_ip:
  &cc_ip_value 127.0.0.1

network_interface: eth0


compute_nodes:
 - localhost
 - *cc_ip_value



nova:
  rpm_packages: openstack-nova-node-full
  conf_file: /etc/nova/nova.conf

db:
  admin: root
  admin_pwd: nova
  name: nova
  user: nova
  password: nova

user:
  name: admin1

project:
  name: project1

network:
  cidr: 172.30.252.0/22
  nets: 1
  ips:  1024

image:
  path: images/ttylinux.tar.gz
  url: http://127.0.0.1/images/rhel_image.tar.gz
  disk: rootfs.raw
  ram: initramfs-2.6.32-131.0.15.el6.x86_64.img
  kernel: vmlinuz-2.6.32-131.0.15.el6.x86_64
  name: rhel_image

vm:
  user: root
  flavor: m1.tiny
  name: "rhel_instance1"
  boot_timeout: 60
  ping_deadline: 30
  keypair:
    name: test_key
    private: id_rsa_generated
    public:  id_rsa_generated.pub

vm2:
  user: root
  flavor: m1.tiny
  name: "rhel_instance2"
  boot_timeout: 180
  ping_deadline: 30


instance1: ins1
instance2: ins2

openstack_services:
 - nova-api
 - nova-direct-api
 - nova-compute
 - nova-network
 - nova-scheduler
 - openstack-glance-api
 - openstack-glance-registry

supplementary_services:
 - rabbitmq-server
 - mysqld
 - libvirtd

test_prepequisites:
 - tar
 - grep
 - sed
 - gawk
 - unzip
 - openssh-clients
 - openssh
 - nc
 - wget
 - curl
 - nmap
 - pexpect

packages_to_install:
 - libvirt
 - mysql
 - mysql-server
 - rabbitmq-server
 - openstack-nova-node-full
 - MySQL-python

packages_to_clean:
 - django-file-upload
 - django-openstack
 - django-openstack-vnc
 - openstack-client
 - openstack-client-doc
 - openstack-compute
 - openstack-dashboard
 - openstack-glance
 - openstack-glance-doc
 - openstack-keystone
 - openstack-nova
 - openstack-nova-api
 - openstack-nova-cc-config
 - openstack-nova-compute
 - openstack-nova-compute-config
 - openstack-nova-doc
 - openstack-nova-instancemonitor
 - openstack-nova-network
 - openstack-nova-node-compute
 - openstack-nova-node-full
 - openstack-nova-noVNC
 - openstack-nova-objectstore
 - openstack-nova-scheduler
 - openstack-nova-volume
 - openstackx
 - python-glance
 - python-nova
 - python-novaclient
 - openstack-swift

dep_wildcards_to_clean:
 - '*qemu*'
 - '*libvirt*'
 - '*guestfs*'
 - '*openstack*'
 - '*nova*'
 - '*glance*'
 - '*swift*'
 - '*keystone*'
 - '*eventlet*'

processes_to_kill:
 - 'qemu-kvm'
 - 'dnsmasq'

state_files:
 - '/etc/libvirt'
 - '/var/lib/libvirt'
 - '/var/log/libvirt'
 - '/var/lib/keystone/keystone.{,token.}db'
 - '/var/log/keystone/'
 - '/var/lib/nova'
 - '/var/log/nova'
 - '/etc/nova'
 - '/var/lib/glance'
 - '/var/log/glance'
 - '/etc/glance'
 - '/var/log/rabbitmq/'
 - '/var/lib/rabbitmq/'
 - '/tmp/.guestfs*'
 - '/tmp/tmp*'

volume:
  source_dev:  '/dev/loop4'
  source_dev_file: '/tmp/loop4'
  source_dev_size: 1
  group: nova-volumes
  name1:   vol1
  dev1:   '/dev/vdb'
  size1: 1
  zone: nova
  attach_deadline: 60

volume_packages:
 - scsi-target-utils
 - lvm2
 - openstack-nova-volume

volume_services1:
 - tgtd

volume_services2:
 - nova-volume
